/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  jsDocsSidebar: [
    { id: 'intro', type: 'doc', label: "Guardrails JS" },
    { id: 'installation', type: 'doc', label: "Installation" },
    { id: 'getting-started', type: 'doc', label: "Getting Started" },    
    { type: 'category', label: 'How-To Guides', collapsed: true, items: [
      { type: 'autogenerated', dirName: 'how-to-guides' },
    ]},
    { type: 'category', label: 'Examples', collapsed: true, items: [
      { type: 'autogenerated', dirName: 'examples' },
    ]},
    { type: 'category', label: 'JS Reference', collapsed: true, items: [
      { type: 'autogenerated', dirName: 'js-ref' },
    ]},
    { id: 'faq', type: 'doc', label: "FAQ" },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;